# Generated by Django 4.2.17 on 2025-01-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='pascal_code',
            field=models.CharField(blank=True, help_text='Pascal code', max_length=5000),
        ),
        migrations.AlterField(
            model_name='history',
            name='python_code',
            field=models.CharField(blank=True, help_text='Python code', max_length=5000),
        ),
        migrations.AlterField(
            model_name='history',
            name='translating_errors',
            field=models.CharField(blank=True, help_text='Translating errors', max_length=300),
        ),
        migrations.AlterField(
            model_name='history',
            name='translating_info',
            field=models.CharField(blank=True, help_text='Translating information', max_length=150),
        ),
    ]
