# Generated by Django 4.2.17 on 2025-01-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_history_pascal_code_alter_history_python_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='req_date',
            field=models.DateTimeField(blank=True, help_text='Time and date of request'),
        ),
    ]
