# Generated by Django 4.2.17 on 2025-01-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_history_req_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='req_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Time and date of request'),
        ),
    ]
